name: data_input_package
description: General purpose widget for entering passwords and text
version: 0.0.4+4
author: Steven Smith

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  theme_package:
    path: ../theme_package
  cupertino_icons: ^1.0.0
  equatable: ^1.2.5
  flutter_bloc: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
