name: data_input_package
description: General purpose widget for entering passwords and text
version: 0.0.2
author: Steven Smith

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.22.4"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  equatable: ^1.2.5
  flutter_bloc: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
